/* tslint:disable */
/* eslint-disable */
/**
 * AAS Generator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CreateAasRequest, CreateAasResponse } from '../models/index';

/**
 *
 */
export interface AasCreatorCreateAasRequest {
    assetIdShort: string;
    body?: CreateAasRequest;
}

/**
 * AasCreatorApi - interface
 *
 * @export
 * @interface AasCreatorApiInterface
 */
export interface AasCreatorApiInterface {
    /**
     * Creates a new AAS for a given assetIdShort with optional submodels. If submodel parameters are provided in the request body, submodels will be generated and attached to the AAS.
     * @summary Creates a new AAS with optional submodels
     * @param {string} assetIdShort The assetIdShort to be used for creating the AAS.
     * @param {CreateAasRequest} [body] Optional request body containing BlueprintsIds, Data, and Language for submodel generation.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AasCreatorApiInterface
     */
    aasCreatorCreateAasRaw(
        requestParameters: AasCreatorCreateAasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<CreateAasResponse>>;

    /**
     * Creates a new AAS for a given assetIdShort with optional submodels.
     */
    aasCreatorCreateAas(
        requestParameters: AasCreatorCreateAasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<CreateAasResponse>;
}

/**
 *
 */
export class AasCreatorApi extends runtime.BaseAPI implements AasCreatorApiInterface {
    /**
     * Creates a new AAS for a given assetIdShort with optional submodels. If submodel parameters are provided in the request body, submodels will be generated and attached to the AAS.
     */
    async aasCreatorCreateAasRaw(
        requestParameters: AasCreatorCreateAasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<CreateAasResponse>> {
        if (requestParameters['assetIdShort'] == null) {
            throw new runtime.RequiredError(
                'assetIdShort',
                'Required parameter "assetIdShort" was null or undefined when calling aasCreatorCreateAas().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // ApiKey authentication
        }

        const response = await this.request(
            {
                path: `/api/v2/AasCreator/{assetIdShort}`.replace(
                    `{assetIdShort}`,
                    encodeURIComponent(String(requestParameters['assetIdShort'])),
                ),
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters['body'] as any,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Creates a new AAS for a given assetIdShort with optional submodels.
     */
    async aasCreatorCreateAas(
        requestParameters: AasCreatorCreateAasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<CreateAasResponse> {
        const response = await this.aasCreatorCreateAasRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
